### ISSUE TITLE
Feedback zum Testat vom 23.4.2015

### ISSUE THREAD

**Issue by KaroBee** [tpe-lecture/group-20#9]
Die Lösung erhält in Summe **90 Punkte**. Siehe folgendes Feedback.

### Positives
* Die Berechnung von total basiert auf der Liste – so wird es auch im realen Leben gemacht.
* Aufteilung der Tests für verschiedene Klassen ist auf verschiedene Dateien aufgeteilt + automatisiert
* Umrechnungspräzision ist in eine Konstante ausgelagert, die auch verwendet wird.
* Keine falschen Signaturen, keine *magischen Werte*

##### JavaDoc ist an einigen Stellen fehlerhaft (-10)
JavaDoc für die Return-Werte für mehrere Methoden in den folgenden Klassen ist fehlerhaft verwendet: Account, Amount, Currency. Die Erklärung, was eine Methode zurückgibt wird wie folgt angegeben: @return *Erklärungstext*
Parameter sind zwar angegeben, aber an vielen Stellen fehlen Erklärungen dazu.

**Comment by scharon** [comment]
Danke für die Rückmeldung
